### ISSUE TITLE
array not supported as a type?

### ISSUE THREAD

**Issue by fhitchen** [thenativeweb/get-graphql-from-jsonschema#295]
Hi,
I got this JSON schema and parsing it barfs with the error

````bash
node_modules/get-graphql-from-jsonschema/build/lib/parseSchema.js:38
        throw new errors.SchemaInvalid(`Structure at '${toBreadcrumb_1.toBreadcrumb(path)}' not recognized.`);
        ^

SchemaInvalid [Error]: Structure at 'Account.T0.accountBalance0.T0' not recognized.
````
my question is, is the type array supported?

````js
{
   "rootName" : "Account",
   "schema" : {
      "#docs" : 177,
      "$schema" : "http://json-schema.org/draft-06/schema",
      "Flavor" : "`baseType` = \"Account\", `deserializationType` = \"c.a.d.m.f...\"",
      "properties" : {
         "accountBalance0" : {
            "#docs" : 177,
            "%docs" : 100,
            "items" : {},
            "maxItems" : 0,
            "minItems" : 0,
            "samples" : [
               []
            ],
            "type" : "array"
         },
         "baseType" : {
            "#docs" : 177,
            "%docs" : 100,
            "samples" : [
               "Account"
            ],
            "type" : "string"
````
I have also found a definition like this that the parser does not like.
````js
         "externalIdentifier" : {
            "#docs" : [
               1,
               176
            ],
            "%docs" : [
               0.56,
               99.43
            ],
            "items" : {},
            "maxItems" : 0,
            "minItems" : 0,
            "samples" : [
               [
                  []
               ],
               [
                  null
               ]
            ],
            "type" : [
               "array",
               "null"
            ]
````
Is this one valid?

**Comment by goloroden** [comment]
Sorry for the delayed answer – yes, arrays are supported.

Could you please come up with a small, executable example program, e.g. in a repository, and provide a link to it?

**Comment by fhitchen** [comment]
Thank you for answering. Attached please find a really cut down example of the schema which was generated from sample JSON documents in a Couchbase database. The original was huge. It appeared that the two "type": "array" objects caused the parser to fail. If I converted them to "string" everything was fine.
 
[problem.tar.gz](https://github.com/thenativeweb/get-graphql-from-jsonschema/files/6480093/problem.tar.gz)

Let me know if you need more information.

Thanks, Francis.

**Comment by yeldiRium** [comment]
Hi @fhitchen,

I see two problems here:

In the first schema you gave above the `accountBalance0`'s `item` schema is not given. We can not generate a GraphQL type for an array whose contents are unknown. That is the reason for the `Structure at 'Account.T0.accountBalance0.T0' not recognized.` message - it points at the item schema inside the `accountBalance0` array.

In the second schema you use the type `type: ["array", "null"]`. Since arrays and objects are the more difficult (and relevant) schemas to translate to GraphQL we recently made the choice not to allow them in joined definitions like that. If you want a sub-schema to be either an array or something else, you need to you `oneOf` or `anyOf`. So the schema for your `externalIdentifier` should look something like this:

```json
"externalIdentifier": {
    "#docs": [
       1,
       176
    ],
    "%docs": [
       0.56,
       99.43
    ],
    "oneOf": [
        {
            "type": "array",
            "items": {},
            "maxItems": 0,
            "minItems": 0,
            "samples": [
               [
                  []
               ],
               [
                  null
               ]
            ]
        },
        {
            "type": "null"
        }
    ]
}
```

Also the `items` schema here still needs content, same as with the first schema.

Hope that helps :)

**Comment by fhitchen** [comment]
I see that now, all of the elements that failed had empty items: tags. I wonder why Couchbase DB's infer statement is generating them like so... 
Thanks for the clarification.
