### ISSUE TITLE
Add support for external refs

### ISSUE THREAD

**Issue by Woodz** [thenativeweb/get-graphql-from-jsonschema#358]
I have a JsonSchema document that includes a reference to https://geojson.org/schema/GeoJSON.json, but this causes an error
`Structure at 'testGeoJson' not recognized`

**Comment by yeldiRium** [comment]
Hi @Woodz :wave: 

Referencing external schemas is a great feature of JsonSchema. However, I am reluctant to include this in this library. It would mean making everything async, to be able to fetch schemas from the internet, and it would introduce the possibility of the conversion failing due to network issues.

We had discussions about supporting the `$ref` field before in #327. I think the best solution for external schemas is to load them yourself and add them to the schema either directly or in the way that @Venryx laid out in their issue.

If you like, you can take over where they left of in #327. In the meantime I will close this issue, since I don't think we'll implement fetching external schemas in this library.
